image: ruby:3.1-alpine

stages:
  - build
  - deploy

before_script:
  - apk update && apk add --no-cache curl bash build-base ruby-dev
  - gem install bundler

build:
  stage: build
  script:
    - bundle install
    - ruby app.rb &  # Ejecutar la aplicación en segundo plano
    - sleep 10
    - curl http://localhost:4567 || exit 1  # Verifica que la aplicación responde

deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yaml --namespace=ci-cd-demo
  only:
    - main
