image: ruby:3.1-alpine

stages:
  - build
  - deploy

before_script:
  # Instalamos kubectl en la imagen Alpine
  - apk update && apk add --no-cache curl bash
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/kubectl
  - kubectl version --client

build:
  stage: build
  script:
    - echo "Building the application"
    - bundle install  # Instalar dependencias Ruby
    - echo "Build completed"

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes"
    - kubectl apply -f deployment.yaml --namespace=ci-cd-demo  # Aplica el despliegue en Kubernetes
  only:
    - main
