apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app
  namespace: ci-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
        - name: sinatra-container
          image: ruby:3.1-alpine
          command: ["ruby", "app.rb"]
          ports:
            - containerPort: 4567
