apiVersion: v1
kind: Service
metadata:
  name: sinatra-app-service
  namespace: ci-cd-demo
spec:
  selector:
    app: sinatra-app
  ports:
    - protocol: TCP
      port: 80          # El puerto externo para acceder al servicio
      targetPort: 4568  # Cambia a 4568
  type: NodePort  # Usamos NodePort para exponer el servicio fuera del clúster
