apiVersion: v1
kind: Service
metadata:
  name: sinatra-app-service
  namespace: ci-cd-demo  # Asegúrate de que el namespace esté definido correctamente
spec:
  selector:
    app: sinatra-app  # Debe coincidir con la etiqueta de los pods en el deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # El puerto externo para acceder al servicio
      targetPort: 4567  # El puerto interno del contenedor donde la aplicación Sinatra está escuchando
  type: NodePort  # Usamos NodePort para exponer el servicio fuera del clúster
