apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app
  namespace: ci-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
        - name: sinatra-container
          image: sinatra-app  # La imagen local que construiste
          ports:
            - containerPort: 4569  # Puerto donde escucha la aplicación
---
apiVersion: v1
kind: Service
metadata:
  name: sinatra-app-service
  namespace: ci-cd-demo
spec:
  selector:
    app: sinatra-app
  ports:
    - protocol: TCP
      port: 80          # Puerto externo para acceder al servicio
      targetPort: 4569  # Puerto interno donde la aplicación escucha
  type: LoadBalancer  # Usamos LoadBalancer para exponer el servicio fuera del clúster
